### ISSUE TITLE
Constant crashes

### ISSUE THREAD

**Issue by kasperbjerby** [NeonOrbit/MRVPatchManager#7] opened 2023-10-17 14:44 UTC
Am I the only one that has messenger crashing nearly every time I get a new message? If it's a ongoing conversation and the head stays up, it's fine, but if it has to make a new head it often (not all the time), crashes and sometimes it's like it has reinstalled itself, I open messenger and I have to go through first time install questions and my settings have been reset, is this a common problem? Did I do something wrong?

I am on the new Pixel 8 pro running android 14, I also installed it on my parents phones, and they don't have the same problem, but they are also on Android 13

**Comment by NeonOrbit** [comment] 2023-10-18 00:01
I have yet to try it on android 14. If you know how to take device log (logcat), take it after the crash and submit here.

**Comment by kasperbjerby** [comment] 2023-10-19 13:53
Don't really know how, but I will try 🤗

**Comment by NeonOrbit** [comment] 2023-10-28 00:14
Could you try to patch the latest messenger?

**Comment by dopaemon** [comment] 2023-11-03 15:33
i using Android 14 on Google Pixel 4, and i get random crash

**Comment by NeonOrbit** [comment] 2023-11-20 03:20
The issue is resolved in the latest version of Messenger.

**Closed by NeonOrbit** 2023-11-20 03:20 UTC
